### PR TITLE
manifest updated: BaseApp 24.04 and Runtime 46beta

### PR DESCRIPTION
**Pull request by SudoSu-bham**
Updated pygame to 2.5.2
Update swig to 4.2.1
Update vte to 0.75.92

### CODE REVIEW

**Comment by chimosky** [comment]
Tested, the tree example goes straight to a black screen and doesn't show anything. 

This doesn't happen when tested in Sugar. 
@tchx84 I think we saw something similar a while back, but seeing as he updated pygame it makes me wonder what the possible cause would be.

@SudoSu-bham did this not happen when you tested it?

**Comment by tchx84** [comment]
> Tested, the tree example goes straight to a black screen and doesn't show anything.
> 
> This doesn't happen when tested in Sugar. @tchx84 I think we saw something similar a while back, but seeing as he updated pygame it makes me wonder what the possible cause would be.

@chimosky you mean this one? 

Screenshot from 2024-06-19 19-38-43

> 
> @SudoSu-bham did this not happen when you tested it?

@SudoSu-bham please double check

**Comment by chimosky** [comment]
> > Tested, the tree example goes straight to a black screen and doesn't show anything.
> > This doesn't happen when tested in Sugar. @tchx84 I think we saw something similar a while back, but seeing as he updated pygame it makes me wonder what the possible cause would be.
> 
> @chimosky you mean this one?
> 
> Screenshot from 2024-06-19 19-38-43
> 

Yes, also noticed this warning in the logs although I doubt it has anything to do with the issues.
```bash
(sugarapp:2): VTE-WARNING **: 14:27:04.885: (../src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
```

**Comment by chimosky** [comment]
Tested the stable branch and noticed the same issue, and the same warning above, it has nothing to do with your changes.

**Review by tchx84 — APPROVED** [review]

**Pull request merged**
